config/routes.rb
Rainforest::Application.routes.draw do
  # match '/rate' => 'rater#create', :as => 'rate'

  resources :products do 
    resources :reviews
    member do
      post 'vote'
      post 'unvote'
    end
  end

  # I want to add a route for voting and unvoting to the products resource
  # member resource
  # vs collection resource


  
  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  
  # root :to => 'welcome#index'
  get "/login" => "sessions#new"
  root :to => "users#new"
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents, :category, :poster_name 

  validates :description, :category, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  validates :unique_like_per_user
  
  has_and_belongs_to_many :users, :join_table => 'votes'  # this is actually the like mechanism

  def formatted_price
  	price_in_dollars = price_in_cents.to_f / 100
  	sprintf("%.2f", price_in_dollars)
  end

   has_many :reviews 
   # has_many :users, :through => :reviews

   def unique_like_per_user
   		
   end

  
   
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id, :user_id
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name, :photo_url
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :name

  has_and_belongs_to_many :products, :join_table => 'votes'

  has_many :reviews
  # has_many :products, :through => :reviews 

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # rescue
  #   @current_user = nil
  #   session[:user_id] = nil
  end



  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show]
  before_filter :get_product, :only => [:show, :edit, :destroy, :update, :vote, :unvote]

  def index
  	@products = Product.all

  	respond_to do |format|
  		format.html 
  		format.json { render json: @products}
  	end
  end

  def show
     @reviews = @product.reviews.order("created_at DESC")

    if current_user
      @review = @product.reviews.build
    end

  	respond_to do |format|
  		format.html 
  		format.json { render json: @product}
  	end

  end

  def new
  	@product = Product.new

  	respond_to do |format|
  		format.html 
  		format.json { render json: @products}
  	end
  end

  def edit 
  end

def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
end

  def update 

  	if @product.update_attributes(params[:product])
  		format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
  	else 
  		format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
  	end
  end

  def destroy
  	@product.destroy

  	respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def vote

    @product.users << current_user if !@product.users.include?(current_user)
    redirect_to @product 
  end

  def unvote
    @product.users.destroy(current_user)
    redirect_to @product 
  end

  private
  def get_product
    @product = Product.find(params[:id])
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create                                  
    if current_user.present?
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
	before_filter :load_product


  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(params[:review])
  	@review.user_id = current_user.id

  	if @review.save
  		redirect_to products_path, notice: "Review created successfully"
  	else
  		render :action => :show
  	end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy

  end

  private

  def load_product
  	@product = Product.find(params[:product_id])
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'static'
  
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'static', :only => [:new, :create]
  
  def new
  	@user= User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to products_url, :notice => "Signed Up!"
  	else 
  		render "new"
  	end
  end

  def show
    @user= User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout false
	
	# def index
	# 	render :layout => false
 #  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	# def formatted_price(price_in_cents)
 #  		price_in_dollars = price_in_cents.to_f / 100
 #  		sprintf("$%.2f", price_in_dollars)
 #  	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
    <h1> Rainforest</h1>

     <p>
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
  </div>
 
<div>
  <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
  <% end %>
</div>




<%= yield %>


  <div id="footer">
    <%= image_tag("TO_nobackround.png") %>
  </div>


</body>

</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html class = "landing-page">
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag "static" %>
</head>
<body>
	
			

		<div id = "container">
			<div class = "blue-box">
				<%= yield %>
			</div>
		</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label "Name" %><br>
    <%= f.text_field "name" %>
  </p>
  <p>
    <%= f.label "Description" %><br>
    <%= f.text_field "description" %>
  </p>
  <p>
    <%= f.label "Price in Cents" %><br>
    <%= f.text_field "price_in_cents" %>
  </p>
  <p>
    <%= f.label "Category" %><br>
    <%= f.select :category, [['Music','music'],['Movies','movies'],['Computers', 'computers'],['Other','other']] %>
  </p>

  <p>
    <%= f.submit "Save" %> 
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Photogur </h1>
<h2>Edit a product</h2>

<%= link_to "Back to Products", products_url %>
<%= form_for @product do |f| %>
  <p>
    <%= f.label "Name" %><br>
    <%= f.text_field "name" %>
  </p>
  <p>
    <%= f.label "Description" %><br>
    <%= f.text_field "description" %>
  </p>
  <p>
    <%= f.label "Price in Cents" %><br>
    <%= f.text_field "price_in_cents" %>
  </p>
  <p>
    <%= f.submit "Save" %> 
  </p>
<% end %>

app/views/products/index.html.erb
<h1>Products#index</h1> 

<%= link_to "New Product", "/products/new" %>

<% if current_user %>
<% user= current_user %>
<%= link_to "View My Profile", user_path(user.id) %>
<% end %>

<ul>
<% @products.each do |product| %>
  <li> <p> <%= link_to product[:name], product %> </p> <p><%= product[:description] %></p> <p><%= product[:category] %></p> 
  	<p>Price: $<%= product.formatted_price %></p>
  </li>

<% end %>
</ul>

app/views/products/new.html.erb
<h2>Add a product</h2>

<%= render 'form' %>

<%= link_to "Back to Products", products_path %>

app/views/products/show.html.erb
<h1>Products</h1>

<% if @product.users.include? (current_user) %>
<h1> <%= link_to "UNLIKE", unvote_product_url(@product), method: :post %> </h1>
<% else %>
 <h1> <%= link_to "LIKE", vote_product_url(@product), method: :post %> </h1>
<% end %>

<h1>Likes: <%= @product.users.count %> </h1>

<%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<ul>
<p><li> Product: <%= @product[:name] %> </li> <li>Colour: <%= @product[:description] %></li> <li>Price: $<%= @product.formatted_price %> </li> <li> Category: <%= @product[:category] %> </li> <li> Who added it: <%= @product[:poster_name] %> </li></p>
</ul>

<% if current_user %> 
	<h3> Reviews </h3>

	<p> Reviews for <%= @product.name %> </p>

	<% @reviews.each do |review| %>
		<p>
			<%= review.comment %>
			<br>
			<% if review.user != nil %>
				<em> by <%= review.user.name %> </em>
				Added on: <%= review.created_at %>
			<% end %>
			</br>
		</p>
	<% end %>

  <h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="actions-bigger-btn"><%=submit_tag 'Sign Up' %></div>

    <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "form-signup-left">
           	<div class="field"> 
           		<%= f.text_field :name, {placeholder: 'Name'} %>
          	</div> 
          	<div class="field">
  				<%= f.text_field :email, {placeholder: 'Email'} %>
  			</div>
        
  </div>
  <div class= "form-signup-right">
  			<div class="field">
   			<%= f.password_field :password, {placeholder: 'Password'}%>
  		</div>
          <div class="field">
          	<%= f.password_field :password_confirmation, {placeholder: 'Password Confirmation'}%>
          </div>
          <div class="field">
            <%#= f.label :photo_url %><br/>
            <%#= f.text_field :photo_url %>
          </div>
    </div>
       
<% end %>




 
  

app/views/users/new.html.erb
<!-- <h1>Sign Up</h1> -->
<%= render 'form' %>

app/views/users/show.html.erb
<h1> User Profile </h1>
<ul>
	<li>Name: <%= @user.name %> </li>
	<li>Email: <%= @user.email %> </li>
</ul>
<p> <%= image_tag(@user.photo_url) %> </p>

app/views/welcome/index.html.erb
<html class="landing-page">
<head>
    <meta charset="utf-8">
    <title>Welcome to Rainforest</title>
    <%= stylesheet_link_tag "welcome" %>
</head>
<body>


   <div id="container">

        <h1>Rainforest</h1>

        <% if current_user %>
            <% redirect_to %>
        <% else %>
            <%= render '/sessions/form' %>
        <% end %>
    </div>
 

</body>
</html>